Converting grammar to ONFH, Hellings algorithm
ALanovaya/formal-lang-course pull request #3
Opened 2024-10-21 09:37 UTC by ALanovaya

## Задача 3. Регулярные запросы для всех пар вершин

Полный балл: 5

- [x] Реализовать тип (`AdjacencyMatrixFA`), представляющий конечный автомат в виде разреженной матрицы смежности из [sciPy](https://docs.scipy.org/doc/scipy/reference/sparse.html) (или сразу её булевой декомпозиции) и информации о стартовых и финальных вершинах. У типа должны быть конструктор от `DeterministicFiniteAutomaton` и `NondeterministicFiniteAutomaton` (первый является подклассом второго, так что можно не различать их явно) из [Задачи 2](#задача-2-построение-детерминированного-конечного-автомата-по-регулярному-выражению-и-недетерминированного-конечного-автомата-по-графу).
- [x] Реализовать функцию-интерпретатор для типа `AdjacencyMatrixFA`, выясняющую, принимает ли автомат заданную строку и является ли язык, задающийся автоматом, пустым. Для реализации последней функции рекомендуется использовать транзитивное замыкание матрицы смежности.
  - Требуемые функции:
     ```python
    def accepts(self, word: Iterable[Symbol]) -> bool:
      pass
    def is_empty(self) -> bool:
      pass
    ```
- [x] Используя [разреженные матрицы из sciPy](https://docs.scipy.org/doc/scipy/reference/sparse.html) реализовать **функцию** пересечения двух конечных автоматов через тензорное произведение.
  - Требуемая функция:
     ```python
    def intersect_automata(automaton1: AdjacencyMatrixFA,
             automaton2: AdjacencyMatrixFA) -> AdjacencyMatrixFA:
        pass
    ```
- [x] На основе предыдущей функции реализовать **функцию** выполнения регулярных запросов к графам: по графу с заданными стартовыми и финальными вершинами и регулярному выражению вернуть те пары вершин из заданных стартовых и финальных, которые связанны путём, формирующем слово из языка, задаваемого регулярным выражением.
  - Требуемая функция:
     ```python
    def tensor_based_rpq(regex: str, graph: MultiDiGraph, start_nodes: set[int],
           final_nodes: set[int]) -> set[tuple[int, int]]:
        pass
    ```

  - Для конструирования регулярного запроса и преобразований графа использовать результаты [Задачи 2](#задача-2-построение-детерминированного-конечного-автомата-по-регулярному-выражению-и-недетерминированного-конечного-автомата-по-графу).
  
 ## Задача 4. Регулярные запросы для нескольких стартовых вершин

Полный балл: 8

- [x] Используя [разреженные матрицы из sciPy](https://docs.scipy.org/doc/scipy/reference/sparse.html) реализовать **функцию** достижимости с регулярными ограничениями с несколькими стартовыми вершинами (алгоритм на основе multiple source BFS через линейную алгебру).
  - Для конструирования регулярного запроса и графа использовать [Задачи 2](#задача-2-построение-детерминированного-конечного-автомата-по-регулярному-выражению-и-недетерминированного-конечного-автомата-по-графу).
  - Требуемая функция:
  ```python
  def ms_bfs_based_rpq(regex: str, graph: MultiDiGraph, start_nodes: set[int],
           final_nodes: set[int]) -> set[tuple[int, int]]:
    pass
  ```
 ## Задача 6. Преобразование грамматики в ОНФХ, алгоритм Хеллингса

Полный балл: 10

- [x] Используя [возможности pyformlang для работы с контекстно-свободными грамматиками](https://pyformlang.readthedocs.io/en/latest/usage.html#context-free-grammar) реализовать **функцию** преобразования контекстно-свободной грамматики в ослабленную нормальную форму Хомского (ОНФХ).
  ```python
  def cfg_to_weak_normal_form(cfg: pyformlang.cfg.CFG) -> pyformlang.cfg.CFG:
      pass
  ```
- [x] Реализовать **функцию**, основанную на алгоритме Хеллингса, решающую задачу достижимости между всеми парами вершин для заданного графа и заданной КС грамматики (не обязательно в ОНФХ).
  - Для работы с графом использовать функции из предыдущих задач.
  ```python
  def hellings_based_cfpq(
    cfg: pyformlang.cfg.CFG,
    graph: nx.DiGraph,
    start_nodes: set[int] = None,
    final_nodes: set[int] = None,
  ) -> set[tuple[int, int]]:
     pass
  ```

2024-10-21 10:39 UTC, WoWaster requested changes
За 6 полный балл, 3 и 4 придётся поправить

2024-10-21 10:39 UTC, WoWaster commented on project/fa.py
> +        return np.linalg.matrix_power(combined.toarray(), number_of_states)
Кажется, что конвертировать разреженную матрицу в плотную --- плохая идея

2024-10-21 10:39 UTC, WoWaster commented on project/fa.py
> +        return np.linalg.matrix_power(combined.toarray(), number_of_states)
Это касается примерно всех вызовов функций из numpy

2024-10-21 14:17 UTC, WoWaster requested changes
Окей, я понял, что надо точнее писать чего хочется

2024-10-21 14:17 UTC, WoWaster commented on project/fa.py
> +            lambda: np.zeros((len(self.states), len(self.states)), dtype=bool_)
Ква

2024-10-21 14:17 UTC, WoWaster commented on project/fa.py
> +            return np.eye(number_of_states, dtype=bool_)
Ква-ква

2024-10-21 14:18 UTC, WoWaster commented
Или я пришел раньше реквеста?.. Если так, то извините

2024-10-21 14:18 UTC, ALanovaya commented on project/fa.py
> +            return np.eye(number_of_states, dtype=bool_)
сейчас исправлю)

2024-10-21 14:49 UTC, ALanovaya commented on project/fa.py
> +            return np.eye(number_of_states, dtype=bool_)
Вроде все исправила, там, где были запрошены изменения

2024-10-22 06:57 UTC, WoWaster approved these changes

2024-10-22 07:04 UTC, merged